name: Go Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and Test Go Program
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'  # here am specifying my version.

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
