name: PR Notification Email

on:
  pull_request:
    types: [opened]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: New PR opened in ${{github.repository}}
          body: |
            A new pull request has been opened by ${{github.actor}}.
            
            PR Title: ${{github.event.pull_request.title}}
            PR Description: ${{github.event.pull_request.body}}
            
            You can view the PR here: ${{github.event.pull_request.html_url}}
          to: ${{secrets.EMAIL_RECIPIENTS}}
          from: ${{secrets.EMAIL_USERNAME}}
          secure: true